export const ADD_NEW_ROOM = 'ADD_NEW_ROOM';
export const INCREMANT_ADULTS = 'ADD_ADULTS';
export const INCREMANT_CHILDS = 'ADD_CHILDS';
export const REMOVE_ROOM = 'REMOVE_ROOM';
export const DECREMENT_CHILDS = 'DECREMENT_CHILDS';
export const DECREMENT_ADULTS = 'DECREMENT_ADULTS';
export const ONCHANGE_CHILD_VALUE = 'ONCHANGE_CHILD_VALUE';
export const ONEXPAND_ROOM = 'ONEXPAND_ROOM';

